### ISSUE TITLE
Percentage difference

### ISSUE THREAD

**Issue by phcoetzee** [pwnbus/OctoPrint-Progress-Title#2]
There seems to be a 2% difference between Octoprint progress bar and this OctoPrint-Progress-Title plugin! For an example the OctoPrint-Progress-Title plugin will show 8% while the Octoprint progress bar will show 6%. Thank you BTW.

**Comment by frc001** [comment]
I'm having the same problem but the delta is larger in my case.  I'm seeing a difference of 8-10% completion status difference.  Currently, the title shows 86% complete but the printer and Octoprint show 78%.

**Comment by samster395** [comment]
I can confirm this is happening to me to but I cant seem to figure out why its happening.

Mine is the opposite though, the title is 2-5% behind the progress bar.

**Comment by phcoetzee** [comment]
Update! I had a 8% difference today between the Octoprint progress bar and this OctoPrint-Progress-Title plugin!

**Comment by pwnbus** [comment]
Hmm interesting, I haven't been able to replicate it at all on my end (in both octoprint in development mode, as well as running on my 3d printer).

Is it happening consistently? If you reload the page, does the difference go away?

**Comment by phcoetzee** [comment]
Hi, yes it's happening constantly and no it doesn't get better if I do a F5
refresh.

Regards

Pieter Coetzee

**Comment by pwnbus** [comment]
@phcoetzee Does it happen on all prints for you, or specifically the one? Is it possible for you to send the gcode to me so I can use it for testing?

**Comment by phcoetzee** [comment]
Its happening with all my prints. Sorry cant send you the gcode.

**Comment by qkdefus** [comment]
keep happening to me too, title bar says 3% while octoprint reports 32%
using print time genius plugin, not sure if that affect it

**Comment by qkdefus** [comment]
![ss+(2020-04-07+at+05 37 49)](https://user-images.githubusercontent.com/4680848/78690192-70074000-78f7-11ea-8f7e-5c4566339fbe.png)

**Comment by pwnbus** [comment]
Sorry for a bit of radio silence here.

That's a great point that using something like print time genius might be causing the inconsistency here. I'll see if I can replicate things on my side and if so, will try and come up with a fix.

**Comment by qkdefus** [comment]
Great :) Thanks!

tor. 30. apr. 2020, 21:37 skrev Brandon Myers <notifications@github.com>:

**Comment by pwnbus** [comment]
I was able to replicate this issue when using the PrintTimeGenius plugin in a dev environment, and I believe I've got a fix for this in https://github.com/pwnbus/OctoPrint-Progress-Title/pull/5. 

I'm gonna run a few more tests later this evening when I can get to my printer before I create and push out a release, which will most likely be in a day or two.

If folks are interested in testing the fix in the meantime (which would be greatly appreciated but certainly not expected), you can install it via the manual link `https://github.com/pwnbus/OctoPrint-Progress-Title/archive/fix_progress_percentage.zip` 

Are folks using a printer time improvement plugin that is not PrintTimeGenius? If so, would you mind telling me which one so I can ensure it works with this fix please?

**Comment by peppelorum** [comment]
This solves the issue for me! Well done! =)

**Comment by pwnbus** [comment]
Finally got around to verifying this code, and just created a new release (v0.1.1), thanks for the comments in the issue!
